### PR TITLE
add string and map type to validation

### PR DESCRIPTION
**Pull request by jreidinger**
- https://trello.com/c/TDfgW1oy/1549-8-improve-used-xml-parser
- Parent PR: https://github.com/yast/yast-yast2/pull/1039

Starting point to get impression what changes will be needed in rnc files to allow to specify types everywhere.

Also to get impression how it will look like in autoyast, here is example exported profile, that specifies type everywhere (note especially empty strings in kdump, that was invalid previously and skipped and depending on picking proper default in kdump):

```xml
<?xml version="1.0"?>
<!DOCTYPE profile SYSTEM "">
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
  <deploy_image config:type="map">
    <image_installation config:type="boolean">false</image_installation>
  </deploy_image>
  <kdump config:type="map">
    <add_crash_kernel config:type="boolean">false</add_crash_kernel>
    <crash_kernel config:type="list">
      <listentry config:type="string">203M,high</listentry>
      <listentry config:type="string">72M,low</listentry>
    </crash_kernel>
    <crash_xen_kernel config:type="string">275M\&lt;4G</crash_xen_kernel>
    <general config:type="map">
      <KDUMPTOOL_FLAGS config:type="string"/>
      <KDUMP_COMMANDLINE config:type="string"/>
      <KDUMP_COMMANDLINE_APPEND config:type="string"/>
      <KDUMP_CONTINUE_ON_ERROR config:type="string">true</KDUMP_CONTINUE_ON_ERROR>
      <KDUMP_COPY_KERNEL config:type="string">yes</KDUMP_COPY_KERNEL>
      <KDUMP_CPUS config:type="string">1</KDUMP_CPUS>
      <KDUMP_DUMPFORMAT config:type="string">lzo</KDUMP_DUMPFORMAT>
      <KDUMP_DUMPLEVEL config:type="string">31</KDUMP_DUMPLEVEL>
      <KDUMP_FREE_DISK_SIZE config:type="string">64</KDUMP_FREE_DISK_SIZE>
      <KDUMP_HOST_KEY config:type="string"/>
      <KDUMP_IMMEDIATE_REBOOT config:type="string">yes</KDUMP_IMMEDIATE_REBOOT>
      <KDUMP_KEEP_OLD_DUMPS config:type="string">5</KDUMP_KEEP_OLD_DUMPS>
      <KDUMP_KERNELVER config:type="string"/>
      <KDUMP_NETCONFIG config:type="string">auto</KDUMP_NETCONFIG>
      <KDUMP_NET_TIMEOUT config:type="string">30</KDUMP_NET_TIMEOUT>
      <KDUMP_NOTIFICATION_CC config:type="string"/>
      <KDUMP_NOTIFICATION_TO config:type="string"/>
      <KDUMP_POSTSCRIPT config:type="string"/>
      <KDUMP_PRESCRIPT config:type="string"/>
      <KDUMP_REQUIRED_PROGRAMS config:type="string"/>
      <KDUMP_SAVEDIR config:type="string">file:///var/crash</KDUMP_SAVEDIR>
      <KDUMP_SMTP_PASSWORD config:type="string"/>
      <KDUMP_SMTP_SERVER config:type="string"/>
      <KDUMP_SMTP_USER config:type="string"/>
      <KDUMP_TRANSFER config:type="string"/>
      <KDUMP_VERBOSE config:type="string">3</KDUMP_VERBOSE>
      <KEXEC_OPTIONS config:type="string"/>
    </general>
  </kdump>
  <networking config:type="map">
    <dns config:type="map">
      <dhcp_hostname config:type="boolean">false</dhcp_hostname>
    </dns>
    <ipv6 config:type="boolean">true</ipv6>
    <keep_install_network config:type="boolean">true</keep_install_network>
    <managed config:type="boolean">true</managed>
  </networking>
  <partitioning config:type="list">
    <drive config:type="map">
      <device config:type="string">/dev/nvme0n1</device>
      <disklabel config:type="string">gpt</disklabel>
      <enable_snapshots config:type="boolean">false</enable_snapshots>
      <initialize config:type="boolean">false</initialize>
      <partitions config:type="list">
        <partition config:type="map">
          <create config:type="boolean">true</create>
          <filesystem config:type="symbol">vfat</filesystem>
          <format config:type="boolean">true</format>
          <mount config:type="string">/boot/efi</mount>
          <mountby config:type="symbol">uuid</mountby>
          <partition_id config:type="integer">259</partition_id>
          <partition_nr config:type="integer">1</partition_nr>
          <resize config:type="boolean">false</resize>
          <size config:type="string">524288000</size>
        </partition>
        <partition config:type="map">
          <create config:type="boolean">true</create>
          <filesystem config:type="symbol">xfs</filesystem>
          <format config:type="boolean">true</format>
          <mount config:type="string">/</mount>
          <mountby config:type="symbol">uuid</mountby>
          <partition_id config:type="integer">131</partition_id>
          <partition_nr config:type="integer">2</partition_nr>
          <resize config:type="boolean">false</resize>
          <size config:type="string">509437018112</size>
        </partition>
        <partition config:type="map">
          <create config:type="boolean">true</create>
          <filesystem config:type="symbol">swap</filesystem>
          <format config:type="boolean">true</format>
          <mount config:type="string">swap</mount>
          <mountby config:type="symbol">uuid</mountby>
          <partition_id config:type="integer">130</partition_id>
          <partition_nr config:type="integer">3</partition_nr>
          <resize config:type="boolean">false</resize>
          <size config:type="string">2147819008</size>
        </partition>
      </partitions>
      <type config:type="symbol">CT_DISK</type>
      <use config:type="string">all</use>
    </drive>
  </partitioning>
</profile>
```

### CODE REVIEW

**Comment by mvidner** [comment]
If you look at this from the user view point, it becomes clear that adding `config:type="string"` is a major pain. Not only having to write it, but also seeing it in the exported files. So we should solve it with this rule:

> If an element does not have child elements, it is a string by default.

**Comment by jreidinger** [comment]
@mvidner so basically you are saying that empty hash always has to use config:type=map and string is always default unless there are children?

**Comment by mvidner** [comment]
>  empty hash always has to use config:type=map and string is always default unless there are children

@jreidinger right

**Comment by jreidinger** [comment]
> > empty hash always has to use config:type=map and string is always default unless there are children
> 
> @jreidinger right

Question is if you should allow in schema to have optionally also that string type ( which this change do ) or if we should forbid it ( current state ). As we need to touch schema due to map already, I am more for allowing it or at least change text to that STRING, so we can easily change it in future.

**Comment by mvidner** [comment]
Yes we will need to update the schema: originally I thought we could make it in a backward compatible way (using another namespace) but it turns out that foreign namespaces are not valid in a RelaxNG document (as opposed to a RelaxNG *schema*).

So yes, `config:type="string"` should be allowed but not required.

> or at least change text to that STRING, so we can easily change it in future.

I don't understand. Do you mean allowing `config:type="any_future_type"` in the schema?

**Comment by jreidinger** [comment]
@mvidner no, I mean using STRING instead of text as it is now in specific elements. If we already use STRING for given type, we can modify one place, but now we need to replace almost all `text` elements.

**Comment by mvidner** [comment]
Ah, the `STRING` define, OK.

**Comment by mvidner** [comment]
@jreidinger I have added `t` and `type` to the schema.

Unfortunately the RNG syntax has become cluttered with namespace URLs, but people are used to XML pain already.

**Pull request merged**
